.\"
.\" cfg - Utility to version-control machine and user configurations.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"
.\"     @(#)cfg.8
.\" $FreeBSD$
.\"
.Dd September 20, 2024
.Dt CFG 8
.Os
.Sh NAME
.Nm cfg
.Nd version-control user and machine configurations
.Sh SYNOPSIS
.Nm
.Cm Ar <any git command>
.El
.El
